### ISSUE TITLE
Inconsistent handling of elections during the two scrapes is driving me nutty

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#13]
I'm probably missing something obvious here but why is the propositions scrape getting the "type" and "date" but the candidate one isn't?

We need to iron this out to the best degree possible because it's crazy to be cobbling that table together piecemeal between two different scrapes.

I wonder if we should break the election scrape entirely to a different command.

**Comment by palewire** [comment]
Also, I think that thanks to our recent changes the ``election_type`` field is out of whack and the propositions scrape is failing.

**Comment by sahilchinoy** [comment]
This is because the propositions pages have the full date while the candidates pages only have the year.

Previously, we were dealing with this with a function that took the full election name (e.g. "2010 SPECIAL ELECTION (ASSEMBLY 43)") and extracting just the election type ("SPECIAL_ELECTION"). The combination of year and election type should be unique.

But yeah, this is sort of crazy. One way to deal with this would be to create two ScrapedElection models, one for the candidates and one for the propositions, and deal with reconciling them (in a manner similar to above) in the processing step.

**Comment by sahilchinoy** [comment]
I split our `ScrapedElection` model into a `CandidateScrapedElection` and a `PropositionScrapedElection` model. Next is reconciling these two as part of the processing step. 

Do you think we should create another management command that does this in Python, or somehow accomplish this with SQL as part of our `processcalaccessdata` command? @gordonje, any thoughts on this?
