### ISSUE TITLE
How much do we care about scraping candidate committees?

### ISSUE THREAD

**Issue by sahilchinoy** [california-civic-data-coalition/django-calaccess-processed-data#21]
Scraping each candidate page to get info on their candidate committees is taking a LOT of time. As far as I remember, this is something that we wanted to confirm the links in the raw data, and isn't adding any new information. We can save time and complexity by killing this; we'd still be able to assemble a list of certified candidates and the offices for which they ran. Thoughts?

**Comment by palewire** [comment]
James and I discussed it on the call this morning. You're right that the committee links are not necessary to verify the certified candidate list. 

However, we'd still like to collect each candidates list of committees as at least a one-time pull so that we can confirm that the links we're making "internally" from the database dump are accurate.

**Comment by sahilchinoy** [comment]
Got it. Then I think I’ll break that scrape into a separate command.
